### ISSUE TITLE
segmentation fault installing Frigate LXC

### ISSUE THREAD

**Issue by alberanid** [tteck/Proxmox#2830]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Frigate LXC shows a segmentation fault error at the **Set Up Hardware Acceleration** step.

The host system is based on Intel 12th gen hardware, without Google Coral or any other TPU.

After the error is shown, the installation proceeds and the software seems to work properly.

### What settings are you currently utilizing?

Default Settings

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
    ______     _             __
   / ____/____(_)___ _____ _/ /____
  / /_  / ___/ / __ `/ __ `/ __/ _ \
 / __/ / /  / / /_/ / /_/ / /_/  __/
/_/   /_/  /_/\__, /\__,_/\__/\___/
             /____/

Using Default Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 0
Using Root Password: Automatic Login
Using Container ID: 106
Using Hostname: frigate
Using Disk Size: 20GB
Allocated Cores 4
Allocated Ram 4096
Using Bridge: vmbr0
Using Static IP Address: dhcp
Using Gateway IP Address: Default
Using Apt-Cacher IP Address: Default
Disable IPv6: No
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server Address: Host
Using MAC Address: Default
Using VLAN Tag: Default
Enable Root SSH Access: No
Enable Verbose Mode: No
Creating a Frigate LXC using the above default settings
 ✓ Using local for Template Storage.
 ✓ Using local-zfs for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 106 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 10.42.30.230 
 ✓ IPv4 Internet Connected
 ✗ IPv6 Internet Not Connected
 ✓ DNS Resolved github.com to 140.82.121.3
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Installed Python3 Dependencies
 ✓ Installed Node.js
 ✓ Installed go2rtc
 ✓ Set Up Hardware Acceleration
 - Installing Frigate v0.13.2 (Perseverance)  \/dev/stdin: line 51: 23658 Segmentation fault      sleep 0.2
/dev/stdin: line 37: 23659 Segmentation fault      sleep 0.2

[ERROR] in line 57: exit code 0: while executing command sleep 0.2
 ✓ Installed Frigate v0.13.2
 ✓ AVX Support Detected
 ✓ Installed Openvino Object Detection Model
 ✓ Installed Coral Object Detection Model
 ✓ Built Nginx
 ✓ Configured Services
 ✓ Customized Container
 ✓ Cleaned
 ✓ Set Container to Normal Resources
 ✓ Completed Successfully!
```

### Please provide detailed steps to reproduce the issue.

Run `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/frigate.sh)"` from the node shell.

**Comment by tteck** [comment]
It has something to do with the spinner, this is the only script that is having this issue.

**Comment by tteck** [comment]
Fixed https://github.com/tteck/Proxmox/commit/4ccf823d7abf445c9aac43e217504f9386426b96

**Comment by figadore** [comment]
I'm still getting this error
```
 ✓ Set Up Hardware Acceleration
 |/dev/stdin: line 51: 25722 Segmentation fault      sleep 0.1
/dev/stdin: line 37: 25723 Segmentation fault      sleep 0.1

[ERROR] in line 57: exit code 0: while executing command sleep 0.1
```
I'm running `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/frigate.sh)"`, so I should be picking up the changes in https://github.com/tteck/Proxmox/commit/4ccf823d7abf445c9aac43e217504f9386426b96, right?

**Comment by tteck** [comment]
Yes, I don't understand why it's giving this fault with this script. The search continues.

**Comment by tteck** [comment]
The script continues, correct?

**Comment by tteck** [comment]
Another attempt, https://github.com/tteck/Proxmox/commit/4d3afc012b9faed809fd0e320b44d7a116ac252b

**Comment by figadore** [comment]
Yes, the script continues. Same result from https://github.com/tteck/Proxmox/commit/4d3afc012b9faed809fd0e320b44d7a116ac252b
```
 ✓ Set Up Hardware Acceleration
 //dev/stdin: line 51: 25500 Segmentation fault      sleep 0.1
/dev/stdin: line 37: 25501 Segmentation fault      sleep 0.1

[ERROR] in line 57: exit code 0: while executing command sleep 0.1
 ✓ Installed Frigate v0.13.2
 ```

**Comment by tteck** [comment]
Another attempt https://github.com/tteck/Proxmox/commit/6c4e2aa7fea3e7799223341d0cafea165a778159 https://github.com/tteck/Proxmox/commit/36fd84660150bd0ab83afc53e9262c88a8ac0e4c

**Comment by treverg** [comment]
I assume there is still an issue with this. I ran the install script, and the final message I got in my console was:
msg_info "Installing Frigate $RELEASE (Perseverance)"

I am using default settings, and putting my storage on a NAS (it works fine using a NAS for your other scripts). 



![image](https://github.com/tteck/Proxmox/assets/22897007/536a48db-0175-49d2-9dba-4ae4fcab98aa)
